mysite/myfont/urls.py
from django.urls import path

from . import views

app_name = 'myfont'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('forget/', views.forget, name='forget'),
    path('reset/', views.reset, name='reset'),

    path('index/', views.index, name='index'),
    path('userinfo/', views.userinfo, name='userinfo'),
    path('moduserinfo/', views.moduserinfo, name='moduserinfo'),
    path('activity/', views.activity, name='activity'),
    path('createfont/', views.createfont, name='createfont'),
    path('myfont/', views.myfont, name='myfont'),
    path('showfont/<int:index>/', views.showfont, name='showfont'),
    path('download/<str:level>/', views.download, name='download'),
    
    # 测试用
    path('addCharacter/', views.addCharacter, name='addCharacter'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myfont.urls')),
    path('admin/', admin.site.urls),
]

mysite/myfont/models.py
from django.db import models


# 用户
class User(models.Model):
    email = models.EmailField(max_length=254, unique=True)
    password = models.CharField(max_length=255)
    name = models.CharField(max_length=20)
    regtime = models.DateField(auto_now=True)
    token = models.CharField(max_length=32, default='')
    actcode = models.CharField(max_length=64)
    actstatus = models.BooleanField(default=False)

    def __str__(self):
        return self.email

    class Meta:
        db_table = 'user'   #更改表名


# 字符
class Character(models.Model):
    word = models.CharField(max_length=6, primary_key=True)
    page = models.PositiveSmallIntegerField(default=0)
    row = models.PositiveSmallIntegerField(default=0)
    col = models.PositiveSmallIntegerField(default=0)
    index = models.IntegerField(default=0)
    level = models.CharField(max_length=10, default='一级')

    def __str__(self):
        return self.word

    class Meta:
        db_table = 'character'   #更改表名


# 字符
class User_Char(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    index = models.PositiveSmallIntegerField()
    posttime = models.DateField(auto_now=True)
    turnpoint = models.TextField(default='')
    ctrlpoint = models.TextField(default='')

    class Meta:
        db_table = 'user_char'   #更改表名
        unique_together = ('user', 'character', 'index')

mysite/myfont/views.py
import cv2
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect, StreamingHttpResponse
from django.template import loader
from django.contrib.auth.hashers import make_password, check_password
from django.conf import settings
from django.core.paginator import Paginator
from .models import User, Character, User_Char
from .myimgutil import MyImgUtil, read_images, OneImgProcess, catImg

import os
import time
import random
import numpy as np

###############################################################
def login(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'myfont/login.html/', context)
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        if User.objects.filter(email=email).exists():
            user = User.objects.get(email=email)
            if check_password(password, user.password):
                token = ''
                for i in range(20):
                    s = '1234567890abcdefghijklmnopqrstuvwxyz'
                    token += random.choice(s)
                now_time = int(time.time()) # 共10位
                token = 'TK' + token + str(now_time)
                response = HttpResponseRedirect('/index/')
                response.set_cookie('myfont_token', token, max_age=10000)
                user.token = token
                user.save()
                return response
            else:
                context['error_msg'] = '邮箱或密码错误'
                return render(request, 'myfont/login.html/', context)
        else:
            context['error_msg'] = '邮箱不存在'
            return render(request, 'myfont/login.html/', context)


def logout(request):
    context = {}
    if request.method == 'GET':
        response = HttpResponseRedirect('/login/')
        response.delete_cookie('myfont_token')
        return response
    return render(request, 'myfont/index.html/', context)


def register(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'myfont/register.html/', context)
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password = make_password(password)
        User.objects.create(name=name, email=email, password=password)
        return HttpResponseRedirect('/login/')


def forget(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'myfont/forget.html/', context)
    if request.method == 'POST':
        email = request.POST.get('email')
        if User.objects.filter(email=email).exists():
            #TODO:改成发邮件，然后链接携带参数，跳转到reset.html
            context.update(email=email)
            return render(request, 'myfont/reset.html/', context)
        else:
            context['error_msg'] = '邮箱不存在'
            return render(request, 'myfont/forget.html/', context)


def reset(request):
    context = {}
    if request.method == 'GET':
        #TODO:配套邮件功能
        return render(request, 'myfont/reset.html/', context)
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        if User.objects.filter(email=email).exists():
            user = User.objects.get(email=email)
            user.password = make_password(password)
            user.save()
            return HttpResponseRedirect('/login/')
        else:
            raise Http404('Email does not exist')

###############################################################
def index(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'myfont/index.html/', context)


def userinfo(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'myfont/userinfo.html/', context)


def download(request, level):
    def down_chunk_file_manager(file_path, chuck_size=1024):
        with open(file_path, "rb") as file:
            while True:
                chuck_stream = file.read(chuck_size)
                if chuck_stream:
                    yield chuck_stream
                else:
                    break
    file_path = 'D:\\beifen\\mysite\\myfont\\static\\myfont\\assets\\fontTable\\GB2312_1.pdf'
    file_name = 'GB2312_1.pdf'
    response = StreamingHttpResponse(down_chunk_file_manager(file_path))
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="{0}"'.format(file_name)
    return response


def moduserinfo(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'myfont/moduserinfo.html/', context)
    if request.method == 'POST':
        name = request.POST.get('name')
        password = request.POST.get('password')
        email = request.myfont_user['user_email']
        user = User.objects.get(email=email)
        user.name = name
        user.password = make_password(password)
        user.save()
        return HttpResponseRedirect('/userinfo/')


def activity(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'myfont/activity.html/', context)
    if request.method == 'POST':
        index = request.POST.get('index')
        article = request.POST.get('article')
        context.update(data=article)
        user_id = request.myfont_user['user_id']
        basepath = settings.BASE_PATH
        userpath = basepath + '\\' + str(user_id)
        userprocesspath = userpath + '\\process'
        img_save_path = userpath + '\\result.jpg'
        img_path_list = []
        # user = User.objects.get(id=user_id)
        # for word in article:
        #     if not Character.objects.filter(word=word):
        #         raise Http404('Word does not exist: ' + word)
        #     character = Character.objects.get(word=word)
        #     if not User_Char.objects.filter(user=user, character=character, index=int(index)):
        #         raise Http404('Cannot find this character in font index: ' + index)
        #     user_char = User_Char.objects.get(user=user, character=character, index=int(index))
        #     generate_img(user_char.turnpoint, user_char.ctrlpoint)
        for word in article:
            if not Character.objects.filter(word=word):
                raise Http404('Word does not exist: ' + word)
            character = Character.objects.get(word=word)
            img_path_list.append(userprocesspath + '\\' + index + '\\' + str(character.index) + '_' + str(character.page) + '_' + str(character.row) + '_' + str(character.col) + '.jpg')
        catImg(img_path_list=img_path_list, img_row=1, img_col=len(article), img_save_path=img_save_path)
        result_img_url = 'upload/' + str(user_id) + '/result.jpg'
        context.update(result_img_url=result_img_url)
        return render(request, 'myfont/activity.html/', context)


def createfont(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'myfont/createfont.html/', context)
    if request.method == 'POST':
        user_id = request.myfont_user['user_id']
        # 获取上传的文件以及选择字体库的编号，如果没有文件，则默认为None
        index = request.POST.get('index')
        inputfiles = request.FILES.getlist('inputfiles', None)
        if not inputfiles: 
            raise Http404('no files or directory for upload!')
        basepath = settings.BASE_PATH
        userpath = basepath + '\\' + str(user_id)
        useruploadpath = userpath + '\\upload'
        userprocesspath = userpath + '\\process'
        useroutlinepath = userpath + '\\outline'
        if not os.path.exists(userpath):
            os.makedirs(userpath)
            os.makedirs(useruploadpath)
            os.makedirs(userprocesspath)
            os.makedirs(useroutlinepath)
            for i in range(1, 4):
                os.makedirs(useruploadpath + '\\' + str(i))
                os.makedirs(userprocesspath + '\\' + str(i))
                os.makedirs(useroutlinepath + '\\' + str(i))
        for inputfile in inputfiles:    # 依次处理各个文件
            destination = open(os.path.join(useruploadpath + '\\' + str(index), inputfile.name), 'wb+')
            for chunk in inputfile.chunks():    # 分块写入单个文件
                destination.write(chunk)
            destination.close()
        if imgpreprocess(useruploadpath, userprocesspath, index):
            img2outline(userprocesspath, useroutlinepath, index)
            outline2bezier(useroutlinepath, index, user_id)
            context.update(msg='上传并创建个性字体库成功')
        else:
            context.update(msg='创建字体失败，请上传符合要求的图片')
        return render(request, 'myfont/createfont.html/', context)


def myfont(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'myfont/myfont.html/', context)


def showfont(request, index):
    context = {}
    if request.method == 'GET':
        user_id = request.myfont_user['user_id']
        page = request.GET.get('page', 1)
        page = int(page)
        path = settings.BASE_PATH + '\\' + str(user_id) + '\\process\\' + str(index)
        img_names = read_images(path)
        if len(img_names) == 0:
            return HttpResponseRedirect('/myfont/')
        start = (page - 1) * 20
        end = page * 20 if page * 20 < len(img_names) else len(img_names)
        img_paths = []
        #一页20个图片，分成4个一行
        row = 0
        cnt = 0
        for i in range(start, end):
            if cnt == 0:
                img_paths.append([])
            img_paths[row].append('upload/' + str(user_id) + '/process/' + str(index) + '/' + img_names[i])
            cnt = cnt + 1
            if cnt == 4:
                row = row + 1
                cnt = 0
        context.update(img_paths=img_paths)

        p = Paginator(img_names, 20)
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False

mysite/myfont/templates/myfont/createfont.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<meta content="width=device-width, initial-scale=1.0" name="viewport">
		<title>见字如面</title>
		<meta content="" name="description">
		<meta content="" name="keywords">
		<!-- Favicons -->
		<link href="{% static 'myfont/assets/img/favicon.png' %}" rel="icon">
		<link href="{% static 'myfont/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
		<!-- Google Fonts -->
		<link
			href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
			rel="stylesheet">
		<!-- Vendor CSS Files -->
		<link href="{% static 'myfont/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'myfont/assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
		<link href="{% static 'myfont/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
		<link href="{% static 'myfont/assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
		<link href="{% static 'myfont/assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
		<link href="{% static 'myfont/assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
		<link href="{% static 'myfont/assets/vendor/aos/aos.css' %}" rel="stylesheet">
		<!-- Template Main CSS File -->
		<link href="{% static 'myfont/assets/css/style.css' %}" rel="stylesheet">
		<!-- =======================================================
  * Template Name: Bethany - v2.2.0
  * Template URL: https://bootstrapmade.com/bethany-free-onepage-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
	</head>

	<body>


		<!-- ======= Header ======= -->
		<header id="header" class="fixed-top d-flex align-items-center">
			<div class="container">
				<div class="header-container d-flex align-items-center">
					<div class="logo mr-auto">
						<h1 class="text-light"><a href="{% url 'myfont:index' %}"><span><strong>见字如面</strong></span></a>
						</h1>
					</div>

					<nav class="nav-menu d-none d-lg-block">
						<ul>
							<li><a href="{% url 'myfont:index' %}"><strong>首页</strong></a></li>
							<li><a href="{% url 'myfont:myfont' %}"><strong>我的字体</strong></a></li>
							<li><a href="{% url 'myfont:createfont' %}"><strong>新建字体</strong></a></li>
							<li><a href="{% url 'myfont:activity' %}"><strong>实用界面</strong></a></li>
							<li class="drop-down">
								<a
									href="{% url 'myfont:userinfo' %}"><strong>用户名：{{ request.myfont_user.user_name }}</strong></a>
								<ul>
									<li><a href="{% url 'myfont:logout' %}">退出登录</a></li>
								</ul>
							</li>
						</ul>
					</nav><!-- .nav-menu -->
				</div><!-- End Header Container -->
			</div>
		</header><!-- End Header -->
		<!-- STEP 1 -->


		<section id="portfolio" margin-top="200px">
			<div class="container ">
				<div class="row">
					<h2>
						<h2>&nbsp</h2>
					</h2>
				</div>
				<br>
				<div>
					<h3>第一步：选择字体包 </h3>
				</div>
				<br>
				<div class="row">
					<div class="col-md-6">
						<div class="row">
							<div class="col-md-4">
								<a href="{% url 'myfont:download' '一级' %}">
									<button type="button" class="btn btn-primary btn-lg btn-block">GB2312一级3755个字</button>
								</a>
							</div>
							<div class="col-md-4">
								<button type="button" class="btn btn-primary btn-lg btn-block">敬请期待更多字体包</button>
							</div>
							<!-- <div class="col-md-4">
								<button type="button" class="btn btn-primary btn-lg btn-block">3号字体</button>
							</div> -->
						</div>
						<br>
						<div class="row">
							<!-- <div class="col-md-4">
								<button type="button" class="btn btn-primary btn-lg btn-block">4号字体</button>
							</div>
							<div class="col-md-4">
								<button type="button" class="btn btn-primary btn-lg btn-block">5号字体</button>
							</div>
							<div class="col-md-4">
								<button type="button" class="btn btn-primary btn-lg btn-block">6号字体</button>
							</div> -->
						</div>
					</div>
					<div class="col-md-6">
						<p>点击左方按钮下载字体模板包，pdf格式，下载后自主打印填写，拍照上传。</p>
					</div>

				</div>
			</div>
		</section>
		<!-- 第二步 -->
		<section id="portfolio" margin-top="200px">
			<div class="container ">

				<div>
					<h3>第二步：填写模板表格</h3>
				</div>

				<div class="row">
					<div class="col-lg-6  col-md-6">

						<img src="{% static 'myfont/assets/img/tamplate_first_page_unfilled.jpg' %}" border="10"
							class="img-fluid" alt="">

					</div>
					<div class="col-lg-6 col-md-6">

						<p>模板表格中按照字的对应顺序填写，左边为参考区，右边为填写区，填写完成后请拍照后上传。</p>
						
						<p><strong>填写注意事项：</strong></p>
						<p>1.请用黑色签字笔书写，不可使用铅笔或其他颜色的笔。
						<br>2.尽量保持手写字处于表格的中央，大小适中，笔记清晰，不要压框或越框。
						<br>3.填错不可修改，可重新打印后填写。</P>
						
						<p><strong>拍照注意事项：</strong></p>
						<p>1.只拍填写区域，且画面包含完整边框且不越过白纸（如左图绿色框线为佳）。</p>
					</div>



				</div>

			</div>
			</div>
		</section>
		<!-- STEP 2 -->

		<!-- STEP 3 -->
		<section id="portfolio" margin-top="200px">
			<div class="container ">
				<div>
					<h3>第三步：选择字体仓库并上传模板表</h3>
				</div>
				<br>
				<div class="row">
					<div class="col-md-6">
						<form enctype="multipart/form-data" action="{% url 'myfont:createfont' %}" method="POST"
							class="my-login-validation" novalidate="">
							{% csrf_token %}
							<input type="hidden" name="filetype" value="file">
							<div class="form-group">
								<div class="radio">
									<label>
										<input type="radio" name="index" id="optionsRadios1" value="1" checked>
										1号字体库
									</label>
								</div>
								<div class="radio">
									<label>
										<input type="radio" name="index" id="optionsRadios2" value="2">
										2号字体库
									</label>
								</div>
								<div class="radio">
									<label>
										<input type="radio" name="index" id="optionsRadios3" value="3">
										3号字体库
									</label>
								</div>
							</div>




							<div class="form-group">
								<label for="exampleInputFile"></label>
								<input type="file" multiple="true" accept=".bmp,.png,.jpg,.jpeg" name="inputfiles"
									id="exampleInputFile">
							</div>
							<button type="submit" class="btn btn-primary btn-lg btn-block">点击上传多个文件</button>
						</form>

						<hr>
<!-- 
						<form enctype="multipart/form-data" action="{% url 'myfont:createfont' %}" method="POST"
							class="my-login-validation" novalidate="">
							{% csrf_token %}
							<input type="hidden" name="filetype" value="directory">
							<div class="form-group">
								<label for="exampleInputFile"></label>
								<input type="file" multiple="true" webkitdirectory directory accept="*/*"
									name="inputfiles" id="exampleInputFile">
							</div>
							<button type="submit" class="btn btn-primary btn-lg btn-block">点击上传文件夹</button>
						</form> -->
					</div> <!--col-md-6-->
					<div class="col-md-6">
						<p><strong>字体仓库说明：</strong></p>
						
						<p>1.每个用户拥有3个字体仓库可用使用，存放用户已经生成的字体。
						<br>2.请选择一个字体仓库供本次上传使用，会覆盖原仓库已有字体包。</p>
						
						<p><strong>上传说明：</strong></p>
						
						<p>1.请上传字体模板表中的全部模板，并拍照上传图片。
						<!-- <br>2.请选择一个字体仓库供本次上传使用，会覆盖原仓库已有字体。</p> -->
							
					</div>
				</div> <!--endROW -->

			</div>
		</section>
		<!-- end -->
		<!-- Vendor JS Files -->
		<script src="{% static 'myfont/assets/vendor/jquery/jquery.min.js' %}"></script>
		<script src="{% static 'myfont/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
		<script src="{% static 'myfont/assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
		<script src="{% static 'myfont/assets/vendor/php-email-form/validate.js' %}"></script>
		<script src="{% static 'myfont/assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
		<script src="{% static 'myfont/assets/vendor/counterup/counterup.min.js' %}"></script>
		<script src="{% static 'myfont/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
		<script src="{% static 'myfont/assets/vendor/venobox/venobox.min.js' %}"></script>
		<script src="{% static 'myfont/assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
		<script src="{% static 'myfont/assets/vendor/aos/aos.js' %}"></script>
		<!-- Template Main JS File -->
		<script src="{% static 'myfont/assets/js/main.js' %}"></script>
	</body>

</html>

mysite/myfont/templates/myfont/moduserinfo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  	<meta charset="utf-8">
  	<meta content="width=device-width, initial-scale=1.0" name="viewport">
  	<title>见字如面</title>
  	<meta content="" name="description">
  	<meta content="" name="keywords">
  	<!-- Favicons -->
	<link href="{% static 'myfont/assets/img/favicon.png' %}" rel="icon">
	<link href="{% static 'myfont/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
	<!-- Vendor CSS Files -->
	<link href="{% static 'myfont/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'myfont/assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
	<link href="{% static 'myfont/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
	<link href="{% static 'myfont/assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
	<link href="{% static 'myfont/assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
	<link href="{% static 'myfont/assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
	<link href="{% static 'myfont/assets/vendor/aos/aos.css' %}" rel="stylesheet">
	<!-- Template Main CSS File -->
	<link href="{% static 'myfont/assets/css/style.css' %}" rel="stylesheet">
	<!-- =======================================================
  	* Template Name: Bethany - v2.2.0
  	* Template URL: https://bootstrapmade.com/bethany-free-onepage-bootstrap-theme/
  	* Author: BootstrapMade.com
  	* License: https://bootstrapmade.com/license/
  	======================================================== -->
</head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container">
      <div class="header-container d-flex align-items-center">
        <div class="logo mr-auto">
          <h1 class="text-light"><a href="{% url 'myfont:index' %}"><span><strong>见字如面</strong></span></a></h1>
        </div>

        <nav class="nav-menu d-none d-lg-block">
          <ul>
            <li><a href="{% url 'myfont:index' %}"><strong>首页</strong></a></li>
            <li><a href="{% url 'myfont:myfont' %}"><strong>我的字体</strong></a></li>
            <li><a href="{% url 'myfont:createfont' %}"><strong>新建字体</strong></a></li>
            <li><a href="{% url 'myfont:activity' %}"><strong>实用界面</strong></a></li>
            <li class="drop-down">
              <a href="{% url 'myfont:userinfo' %}"><strong>用户名</strong></a><ul>
                <li><a href="{% url 'myfont:logout' %}">退出登录</a></li>
              </ul>
            </li>
          </ul>
        </nav><!-- .nav-menu -->
      </div><!-- End Header Container -->
    </div>
  </header><!-- End Header -->
<!-- STEP 1 -->
		<section id="portfolio" margin-top="200px">
			<div class="container ">
				<form action="{% url 'myfont:moduserinfo' %}" method="POST" class="my-login-validation" novalidate="">
					{% csrf_token %}
					<div class="row">
						<h2>
							<h2>&nbsp</h2>
						</h2>
					</div>
					<br>
					<div>
						<h3>用户信息</h3>
					</div>
					<!-- 邮箱 -->
					<div class="row">
						</br>
						</div>
					<div class="row">
						<div class="col-lg-1  col-md-1">
						</div>
						<div class="col-lg-2  col-md-2">
							<p align="right"><strong>邮箱：</strong></p>
						</div>
						<div class="col-lg-6  col-md-6">
							<p>{{ request.myfont_user.user_email }}</p>
						</div>
						<div class="col-lg-3 col-md-3">
						</div>
					</div>
					<!-- 昵称 -->
					<div class="row">
						<div class="col-lg-1  col-md-1">
						</div>
						<div class="col-lg-2  col-md-2">
							<p align="right"><strong>昵称：</strong></p>
						</div>
						<div class="col-lg-2  col-md-2">
							<p><input type="text" class="form-control" name="name" value="{{ request.myfont_user.user_name }}"></p>
						</div>
						<div class="col-lg-7  col-md-7">
						</div>
					</div>
					
					<!-- password -->
					<div class="row">
						<div class="col-lg-1  col-md-1">
						</div>
						<div class="col-lg-2  col-md-2">
							<p align="right"><strong>密码：</strong></p>
						</div>
						<div class="col-lg-2  col-md-2">
							<p><input type="password" class="form-control" name="password"></p>
						</div>					
						<div class="col-lg-7  col-md-7">
						</div>
					</div>
					
					<!-- 注册时间 -->
					<div class="row">
						<div class="col-lg-1  col-md-1">
						</div>
						<div class="col-lg-2  col-md-2">
							<p align="right"><strong>注册时间：</strong></p>
						</div>
						<div class="col-lg-6  col-md-6">
							<p>{{ request.myfont_user.user_regtime }}</p>
						</div>
						<div class="col-lg-3 col-md-3">
						</div>
					</div>
					
					
					<div class="row">
						</br>
						</br>
						</br>
						</br>
					</div>
					<div class="row">
						<div class="col-lg-5 col-md-5">
						</div>
						<div class="col-lg-2 col-md-2">
							<button type="submit" class="btn btn-primary btn-lg btn-block">提交修改</button>
						</div>
						<div class="col-lg-5 col-md-5">
						</div>
					</div>
				</form>
				
			</div>
			</div>
		</section>
<!-- end -->
  <!-- Vendor JS Files -->
  <script src="{% static 'myfont/assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'myfont/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'myfont/assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'myfont/assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'myfont/assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'myfont/assets/vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'myfont/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'myfont/assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'myfont/assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'myfont/assets/vendor/aos/aos.js' %}"></script>
  <!-- Template Main JS File -->
  <script src="{% static 'myfont/assets/js/main.js' %}"></script>
</body>

</html>